a beautiful wall clock
atapas/react-play pull request #119
Opened 2022-04-30 08:29 UTC by Deepak8717

# Description

A new project called analog clock has been added. its a beautiful wall clock

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ -] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ -] I have performed a self-review of my own code
- [ -] I have commented my code, particularly in hard-to-understand areas

2022-04-30 11:00 UTC, atapas commented
@Deepak8717 Please create an issue and associate it.

2022-04-30 11:04 UTC, atapas requested changes

2022-04-30 11:04 UTC, atapas commented on src/plays/analog-clock/AnalogClock.jsx
> +  console.log(date.getHours());
Remove console log

2022-04-30 11:04 UTC, atapas commented on src/plays/analog-clock/AnalogClock.jsx
> +  });
The useEffect should not run everytime.

2022-04-30 12:34 UTC, Deepak8717 commented
@atapas done.

2022-05-01 09:22 UTC, atapas approved these changes

2022-05-01 09:26 UTC, merged