Issue 29 add type script support
atapas/react-play pull request #123
Opened 2022-05-01 08:33 UTC by koustov

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

# Checklist:

- [ x] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-01 08:48 UTC, atapas commented
Please check the error log @koustov 

[14:12:32] Cloning github.com/atapas/react-play (Branch: ISSUE-29-Add-TypeScript-support, Commit: f4aabde)
[14:12:32] Cloning completed: 568.72ms
[14:12:33] Installing build runtime...
[14:12:34] Build runtime installed: 1.689s
[14:12:35] Looking up build cache...
[14:12:36] Build Cache not found
[14:12:36] Installing dependencies...
[14:12:36] yarn install v1.22.17
[14:12:36] [1/4] Resolving packages...
[14:12:37] [2/4] Fetching packages...
[14:12:55] [3/4] Linking dependencies...
[14:12:55] warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
[14:12:55] warning "react-helmet > react-side-effect@2.1.1" has incorrect peer dependency "react@^16.3.0 || ^17.0.0".
[14:12:55] warning "react-organizational-chart > @emotion/css > @emotion/babel-plugin@11.7.2" has unmet peer dependency "@babel/core@^7.0.0".
[14:12:55] warning "react-organizational-chart > @emotion/css > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
[14:12:55] warning "react-scripts > tailwindcss@3.0.12" has unmet peer dependency "autoprefixer@^10.0.2".
[14:12:55] warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
[14:12:55] warning "react-scripts > eslint-config-react-app > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
[14:12:55] warning " > react-shimmer-effect@1.0.9" has incorrect peer dependency "react@^16.8.1".
[14:12:55] warning " > react-shimmer-effect@1.0.9" has incorrect peer dependency "react-dom@^16.8.1".
[14:13:11] [4/4] Building fresh packages...
[14:13:16] $ ./node_modules/.bin/gulp build
[14:13:16] [08:43:16] Using gulpfile ~/path0/gulpfile.js
[14:13:16] [08:43:16] Task never defined: build
[14:13:16] [08:43:16] To list available tasks, try running: gulp --tasks
[14:13:16] error Command failed with exit code 1.
[14:13:16] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[14:13:16] Error: Command "yarn install" exited with 1

2022-05-01 08:53 UTC, atapas requested changes
A few questions and additionally do not commit yarn lock

2022-05-01 08:53 UTC, atapas commented on README.md
>  yarn install
Add yarn equivalent command too

2022-05-01 08:53 UTC, atapas commented on gulpfile.js
> +var gulp = require('gulp');
Why gulp is needed?

2022-05-01 08:53 UTC, atapas commented on package.json
> +    "create-play": "plop",
Do we need this post install script

2022-05-01 08:53 UTC, atapas commented on package.json
> +    "gulp": "^4.0.2",
Do we need gulp?

2022-05-03 17:11 UTC, closed without merging

2022-05-03 17:12 UTC, koustov commented
having an issue with this PR. Will recreate one more