Cancel btn text fix issue #157
atapas/react-play pull request #158
Opened 2022-05-07 18:02 UTC by ashutoshdhande

# Description

Issue is fixed by adding extra class and defining it, to avoid clashes with `btn-default` styles if used in future

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Refer to image below
![image](https://user-images.githubusercontent.com/50861363/167266339-39fe3942-ab94-41f6-978f-18defa10c002.png)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

2022-05-07 18:08 UTC, atapas commented
@nirmalkc Could you please review this PR?

2022-05-12 00:51 UTC, nirmalkc approved these changes

2022-05-12 01:02 UTC, nirmalkc commented
Hi @ashutoshdhande 

Please change the CSS class names in search.css from '.btn-default' to 'btn-default-light' in all the 3 instances shown below (203, 217, 218).

![image](https://user-images.githubusercontent.com/6359059/167971205-19b77362-2da5-4924-86c2-0c64a8882748.png)

Also, do the same change in common/modal/index.jsx.

![image](https://user-images.githubusercontent.com/6359059/167971362-1b2f2cc7-c1c5-490e-8f1a-664f69827bd9.png)

Thanks

2022-05-12 03:47 UTC, atapas requested changes
@ashutoshdhande plz take care of the comments

2022-05-16 13:49 UTC, closed without merging