New/dynamic routes
atapas/react-play pull request #233
Opened 2022-05-25 16:37 UTC by Deepak8717

> First thing, PLEASE READ THIS: [ReactPlay Code Review Checklist](https://github.com/atapas/react-play/wiki/ReactPlay-Code-Review-Checklist)

# Description

A new projects to learn about dynamic routes 
a beginner friendly app where you put the meal category in the url and based on the input app shows the relevant recipes.  

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# How Has This Been Tested?

have manually tested each and every functionality along with warnings and errors.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2022-05-26 05:23 UTC, atapas commented
@Deepak8717 Create an issue explaining what is the objective.

2022-05-26 06:30 UTC, atapas commented
@Deepak8717 Is it review ready?

2022-05-26 07:03 UTC, Deepak8717 commented
@atapas yes

2022-05-26 09:09 UTC, atapas reviewed
In the initial state it is not easy to understand what is selected.

![image](https://user-images.githubusercontent.com/3633137/170456936-c50fd84a-43eb-486a-86be-f03a4a53b7c0.png)

2022-05-26 09:09 UTC, atapas commented on src/plays/dynamic-routes/Data.js
> +    name: "Omelette",
Adding some images will make the play look attarctive.

2022-05-26 09:12 UTC, atapas requested changes

2022-05-26 09:12 UTC, atapas commented on src/plays/dynamic-routes/Readme.md
> +to get the url input paramete value we need to tweak the path of the this project in the play-mets.js file
typo play-meta

2022-05-27 03:48 UTC, Deepak8717 commented
@atapas Please check. I have added the images, fixed the responsiveness, fixed initial menu selection bug  and updated readme file.

2022-05-27 04:44 UTC, atapas commented
@Deepak8717 A small one

![image](https://user-images.githubusercontent.com/3633137/170630674-4d4dfa1c-e381-4c7e-a29d-f185e1b272e9.png)

2022-05-27 06:01 UTC, Deepak8717 commented
@atapas done

2022-05-27 06:26 UTC, atapas requested changes

2022-05-27 06:26 UTC, atapas commented on src/plays/dynamic-routes/Readme.md
> +to get the url input parameter value we need to tweak the path of the this project in the play-metas.js file
it is play-meta.js

2022-05-27 06:26 UTC, atapas commented on src/plays/dynamic-routes/Readme.md
> +from ""/plays/dynamic-routes/" to "/plays/dynamic-routes/:menu"
Why two ""?

2022-05-27 06:26 UTC, atapas commented on src/plays/dynamic-routes/Readme.md
> +
Can add links that helped you learn about routing and params.

2022-05-27 08:51 UTC, atapas requested changes

2022-05-27 08:51 UTC, atapas commented on src/plays/dynamic-routes/Readme.md
> +to get the url input parameter value we need to tweak the path of the this project in the play-metas.js file to "/plays/dynamic-routes/:menu"
@Deepak8717 buddy... it is not `play-metas.js`

2022-05-27 09:43 UTC, Deepak8717 commented
@atapas fixed it

2022-05-27 11:15 UTC, atapas approved these changes

2022-05-27 11:15 UTC, merged