Shimmer effect
atapas/react-play pull request #40
Opened 2022-04-17 16:55 UTC by abhikhatri67

# Description

Added shimmer effect in play thumbnails images using [react-shimmer-effect](https://www.npmjs.com/package/react-shimmer-effect) npm package.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested this on a slow 3g network using chrome dev tools.

# Checklist:

- [ ] I have performed a self-review of my own code

2022-04-17 17:39 UTC, atapas requested changes
All good, just one change request. Can you please use yarn and commit the yarn lock file instead?

2022-04-18 09:06 UTC, atapas commented
> All good, just one change request. Can you please use yarn and commit the yarn lock file instead?

@abhikhatri67 Not sure if you got a chance to see this comment.

2022-04-18 16:41 UTC, abhikhatri67 commented
> > All good, just one change request. Can you please use yarn and commit the yarn lock file instead?
> 
> @abhikhatri67 Not sure if you got a chance to see this comment.

@atapas Sure will do that.

2022-04-18 16:44 UTC, abhikhatri67 commented
Done @atapas.

2022-04-19 01:55 UTC, atapas approved these changes
Looks good.

2022-04-19 01:55 UTC, merged

2022-04-19 02:58 UTC, atapas commented
@all-contributors please add @abhishek-gogroup  for Code